TARGET=win.xpl
SOURCES=*.cpp
OBJECTS=*.o

CC=g++
LD=i585-mingw32msvc-g++
CFLAGS=-Wall -I/home/igor/projects/xpsdk/SDK/CHeaders/XPLM -I/usr/i586-mingw32msvc/include/ -std=c++11 -DXPLM200 -DIBM=1 -DAPL=0 -mwindows
LNFLAGS=-L/home/igor/projects/xpsdk/SDK/Libraries/Win
LIBS=/home/igor/projects/xpsdk/SDK/Libraries/Win/XPLM.lib /home/igor/projects/xpsdk/SDK/Libraries/Win/XPWidgets.lib

all: $(TARGET)

.cpp.o:
	$(CC) $(CFLAGS) -c $<
	
$(TARGET): $(OBJECTS)
	i586-mingw32msvc-dllwrap --dllname=$(TARGET) --driver-name=$(LD) $(OBJECTS) $(LIBS)

